version: '3.4'

services:
  cachedb:
    image: redis
    
  jpsage-erp.webapi:
    image: ${DOCKER_REGISTRY-}jpsageerpwebapi
    build:
      context: .
      dockerfile: src/ERP/JPSAGE-ERP.WebAPI/Dockerfile

  cache.api:
    image: ${DOCKER_REGISTRY-}cacheapi
    build:
      context: .
      dockerfile: src/Cache/Cache.API/Dockerfile

